ci: add iOS build and test action
tooploox/KMMSongApp pull request #16
Opened 2020-10-02 11:51 UTC by tomaszczart

https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-UNIT

2020-10-02 15:07 UTC, tomekdz approved these changes

2020-10-05 08:07 UTC, zofnow approved these changes
I was wondering previously why there's no action to build the iOS app next to the one for tests, but I see the updated description now, so nvm :P

2020-10-05 08:33 UTC, wzieba requested changes

2020-10-05 08:33 UTC, wzieba commented on .github/workflows/readme.yml
> +      - uses: actions/checkout@v2
👀 🥇 !

2020-10-05 08:33 UTC, wzieba commented on .github/workflows/readme.yml
> +        run: xcodebuild test -project iosApp/iosApp.xcodeproj -scheme iosApp -destination "platform=iOS Simulator,name=iPhone 11 Pro"
Can we also start ios tests? I think it'll be 
```
./gradlew iosX64Test
```

![image](https://user-images.githubusercontent.com/5845095/95057249-2a84cd80-06f6-11eb-8b1b-b63fe1355c5e.png)

2020-10-05 12:23 UTC, tomaszczart commented on .github/workflows/readme.yml
> +        run: xcodebuild test -project iosApp/iosApp.xcodeproj -scheme iosApp -destination "platform=iOS Simulator,name=iPhone 11 Pro"
@wzieba Sure, added.

2020-10-05 12:24 UTC, wzieba approved these changes

2020-10-05 12:25 UTC, merged